<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/22 19:40:17
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 3,
  'app_max_jobs_on_category' => 5,
));
