<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/20 12:05:30
sfConfig::add(array(
  'mod_category_enabled' => true,
  'mod_category_view_class' => 'sfPHP',
  'mod_category_is_internal' => false,
));
