<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/20 10:12:06

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost; dbname=curso',
  'username' => 'root',
  'password' => '0renato1',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
