<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/19 17:45:11
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
  'mod_job_is_internal' => false,
));
