<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/24 17:53:04
sfConfig::add(array(
  'mod_category_enabled' => true,
  'mod_category_view_class' => 'sfPHP',
  'mod_category_is_internal' => false,
));
