<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/24 17:34:08
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
