generator:
  class: sfPropelGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              JobeetJob
    plural:                JobeetJobs
    route_prefix:          jobeet_job
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
         is_activated: {label: Activo?, help: Lo deja como activo o no}
         is_public : {label: Público, help: Publicarlo en los sitios}
      list:
        max_per_page: 10
        sort: [expires_at, desc]
        title: Administracion de trabajos
        layout: stacked
        display: [company, position, location, url, is_activated, email]
        params:  |
#         %%is_activated%%<small>%%category_id%%</small> - %%company%%
          %%is_activated%%<small>%%jobeet_category%%</small> - %%company%% 
          (<em>%%email%%</em> está buscando: %%=position%% (%%location%%))
      filter:  ~
      form:    ~
      edit:
        title: Editando el trabajo %%company%% que esta buscando un %%position%%
      new:
        title: Creación de trabajos
